---
# defaults file for s3-setup

region: eu-central-1
bucket_name: digital-logistic-web3
file_syncs:
  - name: delivery_status_images
    file_root: ./images
    key_prefix: images
    permission: public-read
    cache_control: "public, max-age=31536000"
    include: "*.png"
  - name: simple_webpage
    file_root: ./frontend
    key_prefix: ""
    permission: public-read
    cache_control: "public, max-age=31536000"
    include: "*.html"
