---
- hosts: localhost
  connection: local
  roles:
    - s3-setup
    - dynamodb
  vars:
    - bucket_name: digital-logistic-web3
    - file_syncs:
        - name: delivery_status_images
          file_root: ./files/images
          key_prefix: images
          permission: public-read
          cache_control: "public, max-age=31536000"
          include: "*.png"
        - name: simple_webpage
          file_root: ./files/frontend
          key_prefix: ""
          permission: public-read
          cache_control: "public, max-age=31536000"
          include: "*.html"
    - tables:
        - name: digital_logistics_parcel_2
          hash_key_name: parcel_id
          hash_key_type: STRING
          range_key_name: parcel_create_time
          range_key_type: STRING
          read_capacity: 2
          write_capacity: 2
          trigger:
            enabled: false
        - name: digital_logistics_customer_2
          hash_key_name: customer_id
          hash_key_type: STRING
          range_key_name: ''
          range_key_type: STRING
          read_capacity: 2
          write_capacity: 2
          trigger:
            enabled: true
            stream_view_type: NEW_AND_OLD_IMAGES
            function_name: update_parcel_status_test
